version: '2'
services:
    documentcar-app:
        image: documentcar
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://documentcar-postgresql:5432/documentCar
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    documentcar-postgresql:
        extends:
            file: postgresql.yml
            service: documentcar-postgresql
